# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.DecisionLogGrantPermissions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"permission",
    :"grantingRole"
  ]

  @type t :: %__MODULE__{
    :"permission" => map() | nil,
    :"grantingRole" => map() | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.DecisionLogGrantPermissions do
  def decode(value, _options) do
    value
  end
end

