# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.AssignedRole do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"role",
    :"tenant"
  ]

  @type t :: %__MODULE__{
    :"role" => String.t,
    :"tenant" => String.t
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.AssignedRole do
  def decode(value, _options) do
    value
  end
end

