# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.DataSourceEntry do
  @moduledoc """
  Data source configuration - where client's should retrive data from and how they should store it
  """

  @derive [Poison.Encoder]
  defstruct [
    :"url",
    :"config",
    :"topics",
    :"dst_path",
    :"save_method"
  ]

  @type t :: %__MODULE__{
    :"url" => String.t,
    :"config" => map() | nil,
    :"topics" => [String.t] | nil,
    :"dst_path" => String.t | nil,
    :"save_method" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.DataSourceEntry do
  def decode(value, _options) do
    value
  end
end

