# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.DataSourceConfig do
  @moduledoc """
  Static list of Data Source Entries returned to client.  Answers this question for the client: from where should i get the full picture of data i need? (as opposed to incremental data updates)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"entries"
  ]

  @type t :: %__MODULE__{
    :"entries" => [PermitIoAPI.Model.DataSourceEntry.t]
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.DataSourceConfig do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"entries", :list, PermitIoAPI.Model.DataSourceEntry, options)
  end
end

