# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.Environment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"id",
    :"projectId"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"id" => String.t,
    :"projectId" => String.t
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.Environment do
  def decode(value, _options) do
    value
  end
end

