# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.HttpValidationError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"detail"
  ]

  @type t :: %__MODULE__{
    :"detail" => [PermitIoAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.HttpValidationError do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"detail", :list, PermitIoAPI.Model.ValidationError, options)
  end
end

