# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.NewOrganization do
  @moduledoc """
  these fields should not be editable once the object is created in db
  """

  @derive [Poison.Encoder]
  defstruct [
    :"slug",
    :"name",
    :"settings"
  ]

  @type t :: %__MODULE__{
    :"slug" => String.t,
    :"name" => String.t,
    :"settings" => map() | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.NewOrganization do
  def decode(value, _options) do
    value
  end
end

