# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.NewResource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"description",
    :"attributes",
    :"name",
    :"path",
    :"actions",
    :"environmentId"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t,
    :"description" => String.t | nil,
    :"attributes" => map() | nil,
    :"name" => String.t,
    :"path" => String.t,
    :"actions" => [PermitIoAPI.Model.NewAction.t] | nil,
    :"environmentId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.NewResource do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"actions", :list, PermitIoAPI.Model.NewAction, options)
  end
end

