# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.NewRemoteUser do
  @moduledoc """
  create user from remote user
  """

  @derive [Poison.Encoder]
  defstruct [
    :"key",
    :"firstName",
    :"lastName",
    :"email",
    :"roles",
    :"attributes"
  ]

  @type t :: %__MODULE__{
    :"key" => String.t,
    :"firstName" => String.t | nil,
    :"lastName" => String.t | nil,
    :"email" => String.t | nil,
    :"roles" => [PermitIoAPI.Model.AssignedRole.t] | nil,
    :"attributes" => map() | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.NewRemoteUser do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"roles", :list, PermitIoAPI.Model.AssignedRole, options)
  end
end

