# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.Organization do
  @moduledoc """
  these fields should not be editable once the object is created in db
  """

  @derive [Poison.Encoder]
  defstruct [
    :"slug",
    :"name",
    :"settings",
    :"id",
    :"created"
  ]

  @type t :: %__MODULE__{
    :"slug" => String.t,
    :"name" => String.t,
    :"settings" => map() | nil,
    :"id" => String.t,
    :"created" => DateTime.t
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.Organization do
  def decode(value, _options) do
    value
  end
end

