# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.Pdp do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"id",
    :"projectId",
    :"environmentId",
    :"clientSecret",
    :"opalToken"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"id" => String.t,
    :"projectId" => String.t,
    :"environmentId" => String.t,
    :"clientSecret" => String.t,
    :"opalToken" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.Pdp do
  def decode(value, _options) do
    value
  end
end

