# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.PermissionSelection do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"permissions"
  ]

  @type t :: %__MODULE__{
    :"permissions" => [PermitIoAPI.Model.PermissionIdentifier.t]
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.PermissionSelection do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"permissions", :list, PermitIoAPI.Model.PermissionIdentifier, options)
  end
end

