# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.Permission do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"scope",
    :"actionId",
    :"resourceId"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"name" => String.t,
    :"scope" => String.t | nil,
    :"actionId" => String.t,
    :"resourceId" => String.t
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.Permission do
  def decode(value, _options) do
    value
  end
end

