# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.PolicyConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userRoles",
    :"rolePermissions"
  ]

  @type t :: %__MODULE__{
    :"userRoles" => %{optional(String.t) => PermitIoAPI.Model.UserRoles.t},
    :"rolePermissions" => %{optional(String.t) => PermitIoAPI.Model.RolePermissions.t}
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.PolicyConfig do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"userRoles", :map, PermitIoAPI.Model.UserRoles, options)
    |> deserialize(:"rolePermissions", :map, PermitIoAPI.Model.RolePermissions, options)
  end
end

