# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.PolicyTopics do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"topics"
  ]

  @type t :: %__MODULE__{
    :"topics" => [String.t]
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.PolicyTopics do
  def decode(value, _options) do
    value
  end
end

