# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.Project do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"description",
    :"settings",
    :"id",
    :"organizationId"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"description" => String.t | nil,
    :"settings" => map() | nil,
    :"id" => String.t,
    :"organizationId" => String.t
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.Project do
  def decode(value, _options) do
    value
  end
end

