# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.RemoteConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"opal_common",
    :"opal_client",
    :"pdp",
    :"context"
  ]

  @type t :: %__MODULE__{
    :"opal_common" => map() | nil,
    :"opal_client" => map() | nil,
    :"pdp" => map() | nil,
    :"context" => map() | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.RemoteConfig do
  def decode(value, _options) do
    value
  end
end

