# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.ResourceDefinitions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"resources"
  ]

  @type t :: %__MODULE__{
    :"resources" => [PermitIoAPI.Model.ResourceDefinition.t]
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.ResourceDefinitions do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"resources", :list, PermitIoAPI.Model.ResourceDefinition, options)
  end
end

