# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.ResourceDefinition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"description",
    :"attributes",
    :"actions"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t,
    :"description" => String.t | nil,
    :"attributes" => map() | nil,
    :"actions" => %{optional(String.t) => PermitIoAPI.Model.ActionProperties.t}
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.ResourceDefinition do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"actions", :map, PermitIoAPI.Model.ActionProperties, options)
  end
end

