# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.Resource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"description",
    :"attributes",
    :"name",
    :"path",
    :"id",
    :"actions",
    :"isBuiltIn"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t,
    :"description" => String.t | nil,
    :"attributes" => map() | nil,
    :"name" => String.t,
    :"path" => String.t,
    :"id" => String.t,
    :"actions" => [PermitIoAPI.Model.Action.t] | nil,
    :"isBuiltIn" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.Resource do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"actions", :list, PermitIoAPI.Model.Action, options)
  end
end

