# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.RolePermissions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"metadata",
    :"permissions"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"metadata" => map() | nil,
    :"permissions" => [PermitIoAPI.Model.PermissionDef.t]
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.RolePermissions do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"permissions", :list, PermitIoAPI.Model.PermissionDef, options)
  end
end

