# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.Role do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"description",
    :"attributes",
    :"settings",
    :"id",
    :"permissions",
    :"isBuiltIn",
    :"environmentId"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"description" => String.t | nil,
    :"attributes" => map() | nil,
    :"settings" => map() | nil,
    :"id" => String.t,
    :"permissions" => [PermitIoAPI.Model.Permission.t] | nil,
    :"isBuiltIn" => boolean() | nil,
    :"environmentId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.Role do
  import PermitIoAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"permissions", :list, PermitIoAPI.Model.Permission, options)
  end
end

