# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.Tenant do
  @moduledoc """
  these fields should not be editable once the object is created in db
  """

  @derive [Poison.Encoder]
  defstruct [
    :"externalId",
    :"name",
    :"description",
    :"settings",
    :"id",
    :"created",
    :"organizationId",
    :"environmentId"
  ]

  @type t :: %__MODULE__{
    :"externalId" => String.t | nil,
    :"name" => String.t,
    :"description" => String.t | nil,
    :"settings" => map() | nil,
    :"id" => String.t,
    :"created" => DateTime.t,
    :"organizationId" => String.t,
    :"environmentId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.Tenant do
  def decode(value, _options) do
    value
  end
end

