# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.UpdateUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"customId",
    :"email",
    :"firstName",
    :"lastName",
    :"attributes",
    :"settings"
  ]

  @type t :: %__MODULE__{
    :"customId" => String.t | nil,
    :"email" => String.t | nil,
    :"firstName" => String.t | nil,
    :"lastName" => String.t | nil,
    :"attributes" => map() | nil,
    :"settings" => map() | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.UpdateUser do
  def decode(value, _options) do
    value
  end
end

