# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PermitIoAPI.Model.UpdateTenant do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"description",
    :"settings"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"description" => String.t | nil,
    :"settings" => map() | nil
  }
end

defimpl Poison.Decoder, for: PermitIoAPI.Model.UpdateTenant do
  def decode(value, _options) do
    value
  end
end

